services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - efub-community-data:/var/lib/mysql
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$${MYSQL_ROOT_PASSWORD}' ]
      interval: 10s
      timeout: 2s
      retries: 100
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: community
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul

  spring:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"

volumes:
  efub-community-data:
